# Generated by Django 5.0.3 on 2024-05-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taygra_app', '0002_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='produtos',
            new_name='produto',
        ),
    ]
