# Generated by Django 5.0.3 on 2024-05-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taygra_app', '0003_rename_produtos_carrinho_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bairro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.CreateModel(
            name='CEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taygra_app.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taygra_app.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taygra_app.estado')),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taygra_app.cep'),
        ),
    ]
