# Generated by Django 5.0.3 on 2024-05-10 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taygra_app', '0005_produto_num_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='quantidade_produto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
